name: build

on:
  push:
    tags:
      - 'v*.*.*'  # 触发于 v1.0.0 等标签

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史，用于生成 release notes

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            g++-12 \
            clang-15 \
            autoconf \
            automake \
            autotools-dev \
            autopoint \
            libtool \
            pkg-config \
            libssl-dev \
            libgnutls28-dev \
            libc-ares-dev \
            zlib1g-dev \
            libsqlite3-dev \
            libssh2-1-dev \
            libcppunit-dev

      - name: Setup gcc (Linux)
        run: |
          echo 'CC=gcc-12' >> $GITHUB_ENV
          echo 'CXX=g++-12' >> $GITHUB_ENV

      - name: Libtool
        run: |
          autoreconf -i

      - name: Disable BitTorrent
        run: |
          FEATURE_FLAGS="$FEATURE_FLAGS --disable-bittorrent"
          echo 'FEATURE_FLAGS='"$FEATURE_FLAGS" >> $GITHUB_ENV

      - name: Autogen and configure for static build
        run: |
          autoreconf -i
          # 使用 LDFLAGS="-static" 来指示链接器优先使用静态库
          # 同时，通过 LIBS 变量和 pkg-config 明确指定需要静态链接的库。
          # 这种方法比 -all-static 更安全，因为它不会强制静态链接系统核心库（如 libc）。
          LDFLAGS="-static" ./configure \
            --enable-static \
            --disable-shared \
            --without-gnutls \
            --with-openssl \
            --with-libssh2 \
            $FEATURE_FLAGS \
            LIBS="$(pkg-config --libs --static openssl zlib libssh2 libcares sqlite3)"

      - name: Build
        run: make -j$(nproc)

      - name: Package binary
        run: |
          strip src/aria2c  # 剥离符号减小文件大小
          tar -czf aria2-${{ github.ref_name }}-linux-x86_64.tar.gz src/aria2c

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            aria2-${{ github.ref_name }}-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
