name: build

on:
  push:
    tags:
      - 'v*.*.*'  # 触发于 v1.0.0 等标签

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史，用于生成 release notes

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            g++-12 \
            clang-15 \
            autoconf \
            automake \
            autotools-dev \
            autopoint \
            libtool \
            pkg-config \
            libssl-dev \
            libgnutls28-dev \
            libc-ares-dev \
            zlib1g-dev \
            libsqlite3-dev \
            libssh2-1-dev \
            libcppunit-dev \
            gettext

      - name: Setup gcc (Linux)
        run: |
          echo 'CC=gcc-12' >> $GITHUB_ENV
          echo 'CXX=g++-12' >> $GITHUB_ENV

      - name: Verify compiler
        run: |
          which gcc-12
          gcc-12 --version
          which g++-12
          g++-12 --version

      - name: Libtool
        run: |
          autoreconf -i

      - name: Disable BitTorrent
        run: |
          FEATURE_FLAGS="$FEATURE_FLAGS --disable-bittorrent"
          echo 'FEATURE_FLAGS='"$FEATURE_FLAGS" >> $GITHUB_ENV

      - name: Configure for static build
        run: |
          # 先尝试基本配置，不使用 -static
          ./configure \
            --enable-static \
            --disable-shared \
            --without-gnutls \
            --with-openssl \
            --with-libssh2 \
            --disable-nls \
            $FEATURE_FLAGS

      - name: Build
        run: make -j$(nproc)

      - name: Create static binary (alternative method)
        run: |
          # 如果上面的方法不行，尝试重新配置为完全静态
          make clean || true
          ./configure \
            --enable-static \
            --disable-shared \
            --without-gnutls \
            --with-openssl \
            --with-libssh2 \
            --disable-nls \
            $FEATURE_FLAGS \
            LDFLAGS="-static -pthread" \
            CPPFLAGS="-I/usr/include" \
            PKG_CONFIG="pkg-config --static"
          make -j$(nproc) LDFLAGS="-all-static"

      - name: Package binary
        run: |
          strip src/aria2c  # 剥离符号减小文件大小
          chmod +x src/aria2c
          tar -czf aria2-${{ github.ref_name }}-linux-x86_64.tar.gz src/aria2c
          
          # 验证二进制文件
          ls -la src/aria2c
          file src/aria2c
          ldd src/aria2c || echo "Static binary (no dynamic dependencies)"

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            aria2-${{ github.ref_name }}-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
